apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp # TO COMPLETE
  ports:
    - port: 80  # Complete with the appropriate port number
      targetPort: 8080 # TO COMPLETE